package tm.charlie.expandabletextview.demo;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.ToggleButton;

import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import tm.charlie.expandabletextview.ExpandableTextView;

import static tm.charlie.expandabletextview.demo.ExtensionsKt.makeClickable; // Generated by Kotlin

public class JavaActivity extends AppCompatActivity{
	ExpandableTextView expandableTextView;
	ToggleButton toggleButton;
	
	@Override
	protected void onCreate(Bundle savedInstanceState){
		super.onCreate(savedInstanceState);
		setTitle(getClass().getSimpleName());
		setContentView(R.layout.java_activity_main);
		
		expandableTextView = findViewById(R.id.expandable_textview);
		toggleButton = findViewById(R.id.toggle_expand);
		
		setupExpandableTextView();
		
		toggleButton.setOnClickListener(new View.OnClickListener(){
			@Override
			public void onClick(View v){
				// Make ExpandableTextView expand/collapse on click
				if (!expandableTextView.isAnimating()) expandableTextView.toggle();
				else toggleButton.toggle();
			}
		});
	}
	
	void setupExpandableTextView(){
		// Make ExpandableTextView expand/collapse on click
		makeClickable(expandableTextView, new Function1<View, Unit>(){
			// OnClickListener
			@Override
			public Unit invoke(View view){
				if (expandableTextView.toggle())// try toggling
					toggleButton.toggle();
				return null;
			}
		});
		expandableTextView.setOnStartExpand(new Function1<ExpandableTextView, Unit>(){
			@Override
			public Unit invoke(ExpandableTextView expandableTextView){
				System.out.println("onStartExpand");
				return null;
			}
		});
		expandableTextView.setOnEndExpand(new Function1<ExpandableTextView, Unit>(){
			@Override
			public Unit invoke(ExpandableTextView expandableTextView){
				System.out.println("onEndExpand");
				return null;
			}
		});
		expandableTextView.setOnStartCollapse(new Function1<ExpandableTextView, Unit>(){
			@Override
			public Unit invoke(ExpandableTextView expandableTextView){
				System.out.println("onStartCollapse");
				return null;
			}
		});
		expandableTextView.setOnEndCollapse(new Function1<ExpandableTextView, Unit>(){
			@Override
			public Unit invoke(ExpandableTextView expandableTextView){
				System.out.println("onEndCollapse");
				return null;
			}
		});
		
	}
}
