package tm.charlie.expandabletextview.demo;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.ToggleButton;

import tm.charlie.expandabletextview.ExpandableTextView;

import static tm.charlie.expandabletextview.demo.ExtensionsKt.makeClickable;
// Generated by Kotlin

public class JavaActivity extends AppCompatActivity{
	@Override
	protected void onCreate(Bundle savedInstanceState){
		super.onCreate(savedInstanceState);
		setContentView(R.layout.java_activity_main);
		
		final ExpandableTextView expandableText = (ExpandableTextView) findViewById(R.id.expandable_textview);
		final ToggleButton toggleButton = (ToggleButton) findViewById(R.id.toggle);
		
		makeClickable(expandableText, false);
		expandableText.setOnClickListener(new View.OnClickListener(){
			@Override
			public void onClick(View v){
				if (expandableText.toggle())// try toggling
					toggleButton.toggle();
			}
		});
		
		toggleButton.setOnClickListener(new View.OnClickListener(){
			@Override
			public void onClick(View v){
				// sync toggle button and expandableTextView states
				if (!expandableText.isAnimating()) expandableText.toggle();
				else toggleButton.toggle();
			}
		});
	}
}
