package tm.charlie.expandabletextview.demo;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.ToggleButton;

import kotlin.Unit;
import kotlin.jvm.functions.Function1;
import tm.charlie.expandabletextview.ExpandableTextView;

import static tm.charlie.expandabletextview.demo.ExtensionsKt.makeClickable; // Generated by Kotlin

public class JavaActivity extends AppCompatActivity{
	@Override
	protected void onCreate(Bundle savedInstanceState){
		super.onCreate(savedInstanceState);
		setTitle(getClass().getSimpleName());
		setContentView(R.layout.java_activity_main);
		
		final ExpandableTextView expandableText = findViewById(R.id.expandable_textview);
		final ToggleButton toggleButton = findViewById(R.id.toggle_expand);
		
		makeClickable(expandableText, new Function1<View, Unit>(){
			// OnClickListener
			@Override
			public Unit invoke(View view){
				if (expandableText.toggle())// try toggling
					toggleButton.toggle();
				return null;
			}
		});
		
		toggleButton.setOnClickListener(new View.OnClickListener(){
			@Override
			public void onClick(View v){
				// sync toggle button and expandableTextView states
				if (!expandableText.isAnimating()) expandableText.toggle();
				else toggleButton.toggle();
			}
		});
	}
}
